//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENOVNIK
    {
        public int id { get; set; }
        public Nullable<double> CenaSat { get; set; }
        public Nullable<double> CenaDan { get; set; }
        public Nullable<int> BrMesta { get; set; }
    }
}
