//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parking_serviceEntities1 : DbContext
    {
        public parking_serviceEntities1()
            : base("name=parking_serviceEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CENOVNIK> CENOVNIKs { get; set; }
        public virtual DbSet<VLASNIK> VLASNIKs { get; set; }
        public virtual DbSet<PARKING> PARKINGs { get; set; }
    }
}
