//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Vreme { get; set; }
        public string RegOznake { get; set; }
        public Nullable<int> idVlasnika { get; set; }
    
        public virtual VLASNIK VLASNIK { get; set; }
    }
}
