//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenziskaStanica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobil()
        {
            this.Benzinskas = new HashSet<Benzinska>();
            this.Pumpas = new HashSet<Pumpa>();
        }
    
        public int id { get; set; }
        public Nullable<int> rezervoar { get; set; }
        public Nullable<int> gorivo { get; set; }
        public Nullable<int> idPumpe { get; set; }
        public Nullable<int> idBenziske { get; set; }
    
        public virtual Benzinska Benzinska { get; set; }
        public virtual Pumpa Pumpa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Benzinska> Benzinskas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pumpa> Pumpas { get; set; }



      
      
    }
}


