//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenziskaStanica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benzinska
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Benzinska()
        {
            this.Automobils = new HashSet<Automobil>();
            this.Pumpas = new HashSet<Pumpa>();
        }
    
        public int id { get; set; }
        public Nullable<int> idAutoput { get; set; }
        public Nullable<int> idAutomobila { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automobil> Automobils { get; set; }
        public virtual Automobil Automobil { get; set; }
        public virtual Autoput Autoput { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pumpa> Pumpas { get; set; }
    }
}
