//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Narandze
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narandze
    {
        public int id { get; set; }
        public Nullable<System.DateTime> CreateadAt { get; set; }
        public Nullable<int> Columns { get; set; }
        public Nullable<int> Rows { get; set; }
        public Nullable<int> Healthy { get; set; }
    }
}
